name: food
channels:
  - conda-forge
dependencies:
  - numpy=1.26.0
  - openpyxl=3.1.2
  - pandas=2.1.3
  - pip=23.3.1
  - python=3.11.6
  - selenium=4.13.0
  - webdriver-manager=4.0.1
  - pip:
    - pyTelegramBotAPI==4.14.0